export const mockProducts = [
  {
    id: 1,
    nome: "Bolo Teste",
    preco_de_venda: 1365.69,
    imagem: null,
    embalagem: {
      id: 2,
      nome: "forma teste",
      local_de_compra: "esquina",
      preco: "0.30",
      atualizado: "2022-08-18",
    },
    receitas: [
      {
        id: 2,
        titulo: "Massa de Batata",
        tamanho: "Grande",
        tipo: "Massa",
        preparo: null,
        custo_receita: 9.742,
        ingredientes: [
          {
            ingrediente: {
              id: 3,
              unidade_medida: "Gramas",
              nome: "açúcar",
              local_de_compra: "atacarejo",
              preco: "3.58",
              atualizado: "2022-07-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 0.179,
            quantidade_utilizada: 50,
          },
          {
            ingrediente: {
              id: 9,
              unidade_medida: "Gramas",
              nome: "amendoim torrado",
              local_de_compra: "casa dos bombons",
              preco: "14.90",
              atualizado: "2022-06-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 1.49,
            quantidade_utilizada: 100,
          },
          {
            ingrediente: {
              id: 10,
              unidade_medida: "Unidade",
              nome: "batata doce",
              local_de_compra: "doca",
              preco: "2.99",
              atualizado: "2020-04-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 8.073,
            quantidade_utilizada: 2700,
          },
        ],
      },
      {
        id: 3,
        titulo: "Massa de Batata",
        tamanho: "Grande",
        tipo: "Massa",
        preparo: null,
        custo_receita: 331.6055,
        ingredientes: [
          {
            ingrediente: {
              id: 2,
              unidade_medida: "Gramas",
              nome: "ácido cítrico",
              local_de_compra: "atacadao",
              preco: "5.75",
              atualizado: "2020-04-01",
              quantidade_embalagem: 40,
            },
            custo_insumo: 7.1875,
            quantidade_utilizada: 50,
          },
          {
            ingrediente: {
              id: 5,
              unidade_medida: "Gramas",
              nome: "açúcar mascavo",
              local_de_compra: "atacarejo",
              preco: "4.18",
              atualizado: "2022-07-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 0.418,
            quantidade_utilizada: 100,
          },
          {
            ingrediente: {
              id: 7,
              unidade_medida: "Gramas",
              nome: "açúcar vanille",
              local_de_compra: "cometa",
              preco: "4.80",
              atualizado: "2020-04-01",
              quantidade_embalagem: 40,
            },
            custo_insumo: 324.0,
            quantidade_utilizada: 2700,
          },
        ],
      },
    ],
  },
  {
    id: 2,
    nome: "Bolo de Rolo",
    preco_de_venda: 1365.69,
    imagem: null,
    embalagem: {
      id: 2,
      nome: "forma xdale",
      local_de_compra: "esquina",
      preco: "0.30",
      atualizado: "2022-08-18",
    },
    receitas: [
      {
        id: 2,
        titulo: "Massa de Batata",
        tamanho: "Grande",
        tipo: "Massa",
        preparo: null,
        custo_receita: 9.742,
        ingredientes: [
          {
            ingrediente: {
              id: 3,
              unidade_medida: "Gramas",
              nome: "açúcar",
              local_de_compra: "atacarejo",
              preco: "3.58",
              atualizado: "2022-07-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 0.179,
            quantidade_utilizada: 50,
          },
          {
            ingrediente: {
              id: 9,
              unidade_medida: "Gramas",
              nome: "amendoim torrado",
              local_de_compra: "casa dos bombons",
              preco: "14.90",
              atualizado: "2022-06-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 1.49,
            quantidade_utilizada: 100,
          },
          {
            ingrediente: {
              id: 10,
              unidade_medida: "Unidade",
              nome: "batata doce",
              local_de_compra: "doca",
              preco: "2.99",
              atualizado: "2020-04-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 8.073,
            quantidade_utilizada: 2700,
          },
        ],
      },
      {
        id: 3,
        titulo: "Massa de Batata",
        tamanho: "Grande",
        tipo: "Massa",
        preparo: null,
        custo_receita: 331.6055,
        ingredientes: [
          {
            ingrediente: {
              id: 2,
              unidade_medida: "Gramas",
              nome: "ácido cítrico",
              local_de_compra: "atacadao",
              preco: "5.75",
              atualizado: "2020-04-01",
              quantidade_embalagem: 40,
            },
            custo_insumo: 7.1875,
            quantidade_utilizada: 50,
          },
          {
            ingrediente: {
              id: 5,
              unidade_medida: "Gramas",
              nome: "açúcar mascavo",
              local_de_compra: "atacarejo",
              preco: "4.18",
              atualizado: "2022-07-01",
              quantidade_embalagem: 1000,
            },
            custo_insumo: 0.418,
            quantidade_utilizada: 100,
          },
          {
            ingrediente: {
              id: 7,
              unidade_medida: "Gramas",
              nome: "açúcar vanille",
              local_de_compra: "cometa",
              preco: "4.80",
              atualizado: "2020-04-01",
              quantidade_embalagem: 40,
            },
            custo_insumo: 324.0,
            quantidade_utilizada: 2700,
          },
        ],
      },
    ],
  },
];
