export const mockSupplies = {
  count: 69,
  next: "http://localhost:8000/api/v1/insumos/?page=2",
  previous: null,
  results: [
    {
      id: 1,
      unidade_medida: "Gramas",
      nome: "abacaxi",
      local_de_compra: "atacadao",
      preco: "3.75",
      atualizado: "2020-04-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 2,
      unidade_medida: "Gramas",
      nome: "ácido cítrico",
      local_de_compra: "atacadao",
      preco: "5.75",
      atualizado: "2020-04-01",
      quantidade_embalagem: 40,
    },
    {
      id: 3,
      unidade_medida: "Gramas",
      nome: "açúcar",
      local_de_compra: "atacarejo",
      preco: "3.58",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 4,
      unidade_medida: "Gramas",
      nome: "açúcar es",
      local_de_compra: "atacadao",
      preco: "2.47",
      atualizado: "2020-04-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 5,
      unidade_medida: "Gramas",
      nome: "açúcar mascavo",
      local_de_compra: "atacarejo",
      preco: "4.18",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 6,
      unidade_medida: "Gramas",
      nome: "açúcar refinado",
      local_de_compra: "atacadao",
      preco: "4.98",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 7,
      unidade_medida: "Gramas",
      nome: "açúcar vanille",
      local_de_compra: "cometa",
      preco: "4.80",
      atualizado: "2020-04-01",
      quantidade_embalagem: 40,
    },
    {
      id: 8,
      unidade_medida: "Gramas",
      nome: "ameixa",
      local_de_compra: "mercadinho pedro",
      preco: "53.00",
      atualizado: "2021-11-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 9,
      unidade_medida: "Gramas",
      nome: "amendoim torrado",
      local_de_compra: "casa dos bombons",
      preco: "14.90",
      atualizado: "2022-06-01",
      quantidade_embalagem: 1000,
    },
  ],
};

export const mockSuppliesEdit = {
  count: 69,
  next: "http://localhost:8000/api/v1/insumos/?page=2",
  previous: null,
  results: [
    {
      id: 1,
      unidade_medida: "Gramas",
      nome: "Abacaxi",
      local_de_compra: "atacadao",
      preco: "3.75",
      atualizado: "2020-04-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 2,
      unidade_medida: "Gramas",
      nome: "ácido cítrico",
      local_de_compra: "atacadao",
      preco: "5.75",
      atualizado: "2020-04-01",
      quantidade_embalagem: 40,
    },
  ],
};
export const mockSuppliesRemove = {
  count: 69,
  next: "http://localhost:8000/api/v1/insumos/?page=2",
  previous: null,
  results: [
    {
      id: 2,
      unidade_medida: "Gramas",
      nome: "ácido cítrico",
      local_de_compra: "atacadao",
      preco: "5.75",
      atualizado: "2020-04-01",
      quantidade_embalagem: 40,
    },
    {
      id: 3,
      unidade_medida: "Gramas",
      nome: "açúcar",
      local_de_compra: "atacarejo",
      preco: "3.58",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 4,
      unidade_medida: "Gramas",
      nome: "açúcar es",
      local_de_compra: "atacadao",
      preco: "2.47",
      atualizado: "2020-04-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 5,
      unidade_medida: "Gramas",
      nome: "açúcar mascavo",
      local_de_compra: "atacarejo",
      preco: "4.18",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 6,
      unidade_medida: "Gramas",
      nome: "açúcar refinado",
      local_de_compra: "atacadao",
      preco: "4.98",
      atualizado: "2022-07-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 7,
      unidade_medida: "Gramas",
      nome: "açúcar vanille",
      local_de_compra: "cometa",
      preco: "4.80",
      atualizado: "2020-04-01",
      quantidade_embalagem: 40,
    },
    {
      id: 8,
      unidade_medida: "Gramas",
      nome: "ameixa",
      local_de_compra: "mercadinho pedro",
      preco: "53.00",
      atualizado: "2021-11-01",
      quantidade_embalagem: 1000,
    },
    {
      id: 9,
      unidade_medida: "Gramas",
      nome: "amendoim torrado",
      local_de_compra: "casa dos bombons",
      preco: "14.90",
      atualizado: "2022-06-01",
      quantidade_embalagem: 1000,
    },
  ],
};

export const mockSupplieID = {
  id: 1,
  unidade_medida: "Gramas",
  nome: "abacaxi",
  local_de_compra: "atacadao",
  preco: "3.75",
  atualizado: "2020-04-30",
  quantidade_embalagem: 1000,
};
